export const ActionTypes = {
    FETCH_YEARS: "FETCH_YEARS",
    ADD_YEAR: "ADD_YEAR",
    DELETE_YEAR: "DELETE_YEAR",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    SET_GRADE: "SET_GRADE",
    DELETE_GRADE: "DELETE_GRADE",
    CREATE_GRADE_SECTION: "CREATE_GRADE_SECTION",
    SET_GRADE_YEAR: "SET_GRADE_YEAR",
    SET_FEEMASTER_TYPES: "SET_FEEMASTER_TYPES",
    GET_YEAR_OF_FEE: "GET_YEAR_OF_FEE",
    POST_YEAR_OF_FEE: "POST_YEAR_OF_FEE",
    DELETE_YEAR_OF_FEE: "DELETE_YEAR_OF_FEE",
    SET_All_VALUES: "SET_All_VALUES",
};
export const Grademastertypes = {
    SET_GRADE_TYPES: " SET_GRADE_TYPES",
};
export const TransportTypes = {
    FETCH_TRANSPORT_FEES: "FETCH_TRANSPORT_FEES",
    DELETE_TRANSPORT_FEES: "DELETE_TRANSPORT_FEES",
    LIST_TRANSPORT_FEES: "LIST_TRANSPORT_FEES",
    ADD_TRANSPORT_FEES: "ADD_TRANSPORT_FEES",
    SET_ACTION_TRANSPORT_FEES: "SET_ACTION_TRANSPORT_FEES",
};
