export const ActionTypes = {
  FETCH_YEARS: "FETCH_YEARS",
  ADD_YEAR: "ADD_YEAR",
  DELETE_YEAR: "DELETE_YEAR",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_GRADE: "SET_GRADE",
  DELETE_GRADE: "DELETE_GRADE",
  CREATE_GRADE_SECTION: "CREATE_GRADE_SECTION",
  SET_GRADE_YEAR: "SET_GRADE_YEAR",
  SET_FEEMASTER_TYPES: "SET_FEEMASTER_TYPES",
  GET_YEAR_OF_FEE: "GET_YEAR_OF_FEE",
  POST_YEAR_OF_FEE: "POST_YEAR_OF_FEE",
  DELETE_YEAR_OF_FEE: "DELETE_YEAR_OF_FEE",
};
export const Grademastertypes = {
  SET_GRADE_TYPES: " SET_GRADE_TYPES",
};
