export const ActionTypes = {
  FETCH_YEARS: "FETCH_YEARS",
  ADD_YEAR: "ADD_YEAR",
  DELETE_YEAR: "DELETE_YEAR",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_GRADE: "SET_GRADE",
  DELETE_GRADE: "DELETE_GRADE",
  CREATE_GRADE_SECTION: "CREATE_GRADE_SECTION",
  SET_GRADE_YEAR: "SET_GRADE_YEAR",
};
export const Grademastertypes = {
  SET_GRADE_TYPES: " SET_GRADE_TYPES",
};
