export const Actiontypes = {
  SET_GRADE: "SET_GRADE",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  CREATE_GRADE_SECTION: "CREATE_GRADE_SECTION",
};
export const Grademastertypes = {
  SET_GRADE_TYPES: " SET_GRADE_TYPES",
};
